# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - oldrel
  - release
  - devel  
  
os:
  - linux
  - osx

matrix:
  exclude:
  - r: devel
    os: osx
#... osx misses some key dependencies 
#    missing: magrittr, Rcpp, stringr
